### ISSUE TITLE
Develop wireframes for individual pages

### ISSUE THREAD

**Issue by dcwebmaven** [CommerceDataService/CDAC_Redesign#5]

**Comment by maabrown** [comment]
As a key stakeholder I will understand and approve the wireframes that give a whole layout of the CDAC site.

## Definition of Done
- [ ] Homepage wireframe modeled 
- [ ] 3 different styles of pages are modeled (Blog, Calendar, Meeting Notes)
- [ ] Styling sheets written

## Acceptance Criteria
- [ ] Can look at colors palette for the page
- [ ] Can click on wireframes to see how information is organized
- [ ] Can explore the website user flow
